### PR TITLE
add authentication

### PR DESCRIPTION
**Pull request by carrotfarmer**
note: Yes, the deployments will **fail.**

you have to add the env vars for the deployments to succeed and add the deployed URL as a safe URL in the firebase portal

ps. i hate javascript

### CODE REVIEW

**Comment by carrotfarmer** [comment]
oh yeah and change the firebase credentials l8r

**Comment by carrotfarmer** [comment]
cz i committed env
and im too lazy to chuck it out

**Review by zsxlver — APPROVED** [review]
Alr looks cool
(yes js makes me mad too)

**Comment by zsxlver** [comment]
okay will change fb creds

**Pull request merged**
